fieldLayouts:
  0b1c92d6-7b48-45ca-bffb-86b094535626:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3d27f701-f1c8-4d49-adf8-3d768934a67d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 16d7d5e4-7801-4ade-b486-ff9be95321ef # About Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 06e8e37f-c89d-4726-8362-0a708cf713ce
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: aba00257-4d79-4442-b22c-9d5062d00454 # Post Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 03fe5260-5995-431d-a1f5-cdfe43e6cc7a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 40b126d0-84b7-4eab-a36d-3944c3505ba0
        userCondition: null
handle: about
hasTitleField: false
name: About
section: 89dc6727-592c-47a8-9ddf-55ca359a7ee9 # About
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
