fieldLayouts:
  1acfeec7-2341-43e8-b6be-2a19450729b2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: e63d4f80-6149-4e05-91c2-fdd84ce8a986
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 68b4ee7e-66ba-4592-b347-b0cdfc5c7567
        userCondition: null
fs: blog
handle: blog
name: Blog
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
