columnSuffix: null
contentColumnType: string
fieldGroup: 750986c8-8b43-4e7d-8cda-746c7c042480 # Blog Post Fields
handle: postContent
instructions: null
name: 'Post Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_postcontent}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
